apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
      - name: sample-webapp
        image: vanshik123docker/sample-webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-service
spec:
  selector:
    app: sample-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30067
  type: NodePort
